slam_toolbox:
  ros__parameters:
    mode: "online_async"
    map_file_name: "map"
    scan_topic: "/scan"
    odom_frame: "odom"
    base_frame: "base_link"
    use_sim_time: false
    use_pose_init: false
#    queue_size: 1500
#    map_update_interval: 2.0  # Valore più alto = meno aggiornamenti
#    processing_threads: 4     # Usa più core CPU
